# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(512, 216)
        self.input_map = QtWidgets.QLineEdit(Dialog)
        self.input_map.setGeometry(QtCore.QRect(20, 130, 75, 25))
        self.input_map.setObjectName("input_map")
        self.input_times = QtWidgets.QLineEdit(Dialog)
        self.input_times.setGeometry(QtCore.QRect(110, 130, 75, 25))
        self.input_times.setObjectName("input_times")
        self.input_item = QtWidgets.QLineEdit(Dialog)
        self.input_item.setGeometry(QtCore.QRect(20, 50, 113, 25))
        self.input_item.setObjectName("input_item")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(200, 50, 300, 135))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 110, 51, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(200, 30, 54, 12))
        self.label_4.setObjectName("label_4")
        self.yesButton2 = QtWidgets.QPushButton(Dialog)
        self.yesButton2.setGeometry(QtCore.QRect(20, 160, 40, 25))
        self.yesButton2.setObjectName("yesButton2")
        self.noButton = QtWidgets.QPushButton(Dialog)
        self.noButton.setGeometry(QtCore.QRect(110, 160, 40, 25))
        self.noButton.setObjectName("noButton")
        self.yesButton = QtWidgets.QPushButton(Dialog)
        self.yesButton.setGeometry(QtCore.QRect(140, 50, 40, 25))
        self.yesButton.setObjectName("yesButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ID"))
        self.label_2.setText(_translate("Dialog", "次数"))
        self.label_3.setText(_translate("Dialog", "装备"))
        self.label_4.setText(_translate("Dialog", "地图"))
        self.yesButton2.setText(_translate("Dialog", "确定"))
        self.noButton.setText(_translate("Dialog", "取消"))
        self.yesButton.setText(_translate("Dialog", "确定"))
